/*
 * Copyright (C) 2012-2026 MotionSystems
 * 
 * This file is part of ForceSeatDI SDK.
 *
 * www.motionsystems.eu
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */

using System;
using System.Runtime.InteropServices;

namespace MotionSystems
{
	public enum FSDI_ModuleErrorCode
	{
		NO_ERROR = 0,

		BOUND                      = 1,
		Z_REF_RUN_GENERAL          = 2,
		Z_REF_RUN_MOTOR_STALL      = 3,
		Z_REF_RUN_TIMEOUT          = 4,
		Z_REF_RUN_Z_MARK_NOT_FOUND = 5,
		Z_REF_RUN_VOLTAGE          = 6,

		BRIDGE_OVERCURRENT              = 7,
		DC_LINE_SHORT_TERM_OVERCURRENT  = 8,
		DC_LINE_LONG_TERM_OVERCURRENT   = 9,
		DC_LINE_HW_OVERCURRENT          = 10,
		OVERVOLTAGE                     = 11,
		MOTION_LOCK_ENGAGED             = 12,
		HV_UNDERVOLTAGE                 = 13,
		DRIVER_PARAMS_NOT_SET           = 14,
		MOTOR_PARAMS_NOT_SET            = 15,
		BRIDGE_OVERHEATED               = 16,
		MOTOR_OVERHEATED                = 17,
		MOTOR_LONG_TERM_OVERCURRENT_I2T = 18,
		FOC_DURATION                    = 19,
		FOC_ERROR                       = 20,
		WOT_ERROR                       = 21,
		BRIDGE_FAILURE                  = 22,
		RBRAKE_FAILURE                  = 23,
		LOGIC_SUPPLY_UNDERVOLTAGE       = 24,

		END_OF_ACTUATOR_NOT_FOUND          = 25,
		FAN_SPEED_INVALID                  = 26,
		HOUSTON_THEY_HAVE_PROBLEM_obsolete = 27,
		NODES_NOT_FOUND                    = 28,

		REF_POS_SENSOR_INITIAL_CHECK_FAILED = 29,
		REF_POS_RUN_TIMEOUT                 = 30,
		REF_POS_RUN_MOTOR_STALL             = 31,
		INCORRECT_DIP_SWITCH_CFG            = 32,

		BRIDGE_UNDERTEMPERATURE    = 33,
		MOTOR_UNDERTEMPERATURE     = 34,
		PENDING_REBOOT             = 35,
		WATCHDOG                   = 36,
		HV_UNDERVOLTAGE_ON_STARTUP = 37,

		TRIAL_MODE_EXPIRED      = 38,
		MOTION_LOCK_COMPROMISED = 39,

		GENERAL_OVERHEATED           = 40,
		COMMUNICATION_ERROR          = 41,
		GENERAL_CONFIG_ERROR         = 42,
		REF_POS_SENSOR_NOT_OPERATING = 43,
		GENERAL_ERROR                = 44,
		GENERAL_NOT_CONNECTED        = 45,
		STALL_DETECTED               = 46,
		EMCY_ENGAGED                 = 47,
		COOLING_SYSTEM_MALFUNCTION   = 48,

		RBRAKE_OVERLOADED              = 49,
		STATIC_OVERVOLTAGE             = 50,
		ACTUATOR_COMMUNICATION         = 51,
		INVALID_UVW_SEQUENCE           = 52,
		DUPLICATED_NODE_ID             = 53,
		VAC_TOO_LOW                    = 54,
		CALIBRATION_MODE_MISMATCH      = 55,
		MOTION_LOCK_FEEDBACK_ERROR     = 56,
		MASTER_MOTION_LOCKED_ACTIVATED = 57,
		POSITION_LIMIT_EXCEEDED        = 58,
		ENCODER_ERROR                  = 59,
		MOTOR_SPEED_INVALID            = 60,
		MISSING_Z_PARAMETER_VALUE      = 61,
		MOTION_LOCK_CYCLE_REQUIRED     = 62,
		UNSUPPORTED_VOLTAGE_ON_STARTUP = 63,

		TWO_CHANNEL_PARKING_PERMANENT_WIRING_ERROR = 253,
		TCOP_PERMANENT_WIRING_ERROR                = 254
	};
}
