/*
 * Copyright (C) 2012-2026 MotionSystems
 * 
 * This file is part of ForceSeatDI SDK.
 *
 * www.motionsystems.eu
 *
 * THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
 * IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
 * FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
 * AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
 * LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
 * OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
 * SOFTWARE.
 */
#ifndef FORCE_SEAT_DI_MODULE_ERROR_CODES_H
#define FORCE_SEAT_DI_MODULE_ERROR_CODES_H

typedef enum FSDI_ModuleErrorCode
{
	FSDI_MEC_NO_ERROR = 0,

	FSDI_MEC_BOUND                      = 1,
	FSDI_MEC_Z_REF_RUN_GENERAL          = 2,
	FSDI_MEC_Z_REF_RUN_MOTOR_STALL      = 3,
	FSDI_MEC_Z_REF_RUN_TIMEOUT          = 4,
	FSDI_MEC_Z_REF_RUN_Z_MARK_NOT_FOUND = 5,
	FSDI_MEC_Z_REF_RUN_VOLTAGE          = 6,

	FSDI_MEC_BRIDGE_OVERCURRENT              = 7,
	FSDI_MEC_DC_LINE_SHORT_TERM_OVERCURRENT  = 8,
	FSDI_MEC_DC_LINE_LONG_TERM_OVERCURRENT   = 9,
	FSDI_MEC_DC_LINE_HW_OVERCURRENT          = 10,
	FSDI_MEC_OVERVOLTAGE                     = 11,
	FSDI_MEC_MOTION_LOCK_ENGAGED             = 12,
	FSDI_MEC_HV_UNDERVOLTAGE                 = 13,
	FSDI_MEC_DRIVER_PARAMS_NOT_SET           = 14,
	FSDI_MEC_MOTOR_PARAMS_NOT_SET            = 15,
	FSDI_MEC_BRIDGE_OVERHEATED               = 16,
	FSDI_MEC_MOTOR_OVERHEATED                = 17,
	FSDI_MEC_MOTOR_LONG_TERM_OVERCURRENT_I2T = 18,
	FSDI_MEC_FOC_DURATION                    = 19,
	FSDI_MEC_FOC_ERROR                       = 20,
	FSDI_MEC_WOT_ERROR                       = 21,
	FSDI_MEC_BRIDGE_FAILURE                  = 22,
	FSDI_MEC_RBRAKE_FAILURE                  = 23,
	FSDI_MEC_LOGIC_SUPPLY_UNDERVOLTAGE       = 24,

	FSDI_MEC_END_OF_ACTUATOR_NOT_FOUND          = 25,
	FSDI_MEC_FAN_SPEED_INVALID                  = 26,
	FSDI_MEC_HOUSTON_THEY_HAVE_PROBLEM_obsolete = 27,
	FSDI_MEC_NODES_NOT_FOUND                    = 28,

	FSDI_MEC_REF_POS_SENSOR_INITIAL_CHECK_FAILED = 29,
	FSDI_MEC_REF_POS_RUN_TIMEOUT                 = 30,
	FSDI_MEC_REF_POS_RUN_MOTOR_STALL             = 31,
	FSDI_MEC_INCORRECT_DIP_SWITCH_CFG            = 32,

	FSDI_MEC_BRIDGE_UNDERTEMPERATURE    = 33,
	FSDI_MEC_MOTOR_UNDERTEMPERATURE     = 34,
	FSDI_MEC_PENDING_REBOOT             = 35,
	FSDI_MEC_WATCHDOG                   = 36,
	FSDI_MEC_HV_UNDERVOLTAGE_ON_STARTUP = 37,

	FSDI_MEC_TRIAL_MODE_EXPIRED      = 38,
	FSDI_MEC_MOTION_LOCK_COMPROMISED = 39,

	FSDI_MEC_GENERAL_OVERHEATED           = 40,
	FSDI_MEC_COMMUNICATION_ERROR          = 41,
	FSDI_MEC_GENERAL_CONFIG_ERROR         = 42,
	FSDI_MEC_REF_POS_SENSOR_NOT_OPERATING = 43,
	FSDI_MEC_GENERAL_ERROR                = 44,
	FSDI_MEC_GENERAL_NOT_CONNECTED        = 45,
	FSDI_MEC_STALL_DETECTED               = 46,
	FSDI_MEC_EMCY_ENGAGED                 = 47,
	FSDI_MEC_COOLING_SYSTEM_MALFUNCTION   = 48,

	FSDI_MEC_RBRAKE_OVERLOADED              = 49,
	FSDI_MEC_STATIC_OVERVOLTAGE             = 50,
	FSDI_MEC_ACTUATOR_COMMUNICATION         = 51,
	FSDI_MEC_INVALID_UVW_SEQUENCE           = 52,
	FSDI_MEC_DUPLICATED_NODE_ID             = 53,
	FSDI_MEC_VAC_TOO_LOW                    = 54,
	FSDI_MEC_CALIBRATION_MODE_MISMATCH      = 55,
	FSDI_MEC_MOTION_LOCK_FEEDBACK_ERROR     = 56,
	FSDI_MEC_MASTER_MOTION_LOCKED_ACTIVATED = 57,
	FSDI_MEC_POSITION_LIMIT_EXCEEDED        = 58,
	FSDI_MEC_ENCODER_ERROR                  = 59,
	FSDI_MEC_MOTOR_SPEED_INVALID            = 60,
	FSDI_MEC_MISSING_Z_PARAMETER_VALUE      = 61,
	FSDI_MEC_MOTION_LOCK_CYCLE_REQUIRED     = 62,
	FSDI_MEC_UNSUPPORTED_VOLTAGE_ON_STARTUP = 63,

	FSDI_MEC_TWO_CHANNEL_PARKING_PERMANENT_WIRING_ERROR = 253,
	FSDI_MEC_TCOP_PERMANENT_WIRING_ERROR                = 254
} FSDI_ModuleErrorCode;

#endif
